name: Validate YAML files

on:
  push:
    paths:
      - "**/*.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get -y install jq nodejs yq
          npm install -g ajv-cli prettier

      - name: Check valid YAML structure
        run: |
          find . -type f -name '*.yml' -exec yq e . {} \; > /dev/null

      - name: Check YAML formatting
        run: |
          prettier --check --tab-width 2 --prove-wrap preserve --no-semi --parser yaml "**/*.yml"

      # - name: Check YAML schema
      #   run: |
      #     for f in `find . -name "*.yml"`; do
      #       ajv validate -s my_schema.json -d $f || exit 1
      #     done
