name: Validate YAML files

on:
  push:
    paths:
      - "**/*.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get -y install yamllint jq nodejs yq
          npm install -g ajv-cli

      - name: Check valid YAML structure
        run: |
          find . -type f -name '*.yml' -exec yq e . {} \; > /dev/null

      - name: Check YAML formatting
        run: |
          yamllint --format parsable --rules="indentation: {spaces: 2, level: 0}" ./**/*.yml | tee indent_violations.txt
          if [ -s indent_violations.txt ]; then exit 1; fi

      # - name: Check YAML schema
      #   run: |
      #     for f in `find . -name "*.yml"`; do
      #       ajv validate -s my_schema.json -d $f || exit 1
      #     done
